mod.target=26.2
deps.fabric_loader=0.19.5
deps.fabric=0.161.0+26.2
deps.modmenu=20.0.2
deps.yacl=3.9.7+26.2-fabric
target.yacl=3.9.7
deps.sodium=xJZxADzI
deps.iris=gxZWWnKH
deps.sodium-extra=kGXOsmfx
deps.moreculling=D5oVCouK
runtime.cloth=Nv3xnWXd

deps.lambdynamiclights=4.12.4+26.2
deps.spruceui=11.0.0+26.2
target.sodium=0.9.2
