mod.target=26.1
mod.target.range=[26.1,26.1.2]

deps.neoforge=26.1.0.19-beta
deps.yacl=3.9.7+26.1-neoforge
deps.lambdynamiclights=4.10.0+26.1
deps.spruceui=10.0.0+26.1
deps.yumi=1.0.0-beta.2+26.1

target.sodium=0.8.9
# Sodium Maven version and matching Iris 1.10.9 Modrinth release.
deps.sodium=0.8.9+mc26.1.1
deps.iris=YEGDGnJM
deps.sodium-extra=kmf7RxIU
deps.moreculling=3pwnQv9b
runtime.cloth=TimoYzse
