mod.target=26.2
mod.icon_key=iconFile
mod.target.range=[26.2]
deps.neoforge=26.2.0.88
deps.yacl=3.9.7+26.2-neoforge
deps.yumi=1.1.1+26.2
deps.sodium=0.9.2+mc26.2
deps.iris=k55HdONq
deps.sodium-extra=jeKkuhSg
deps.moreculling=dKLDGs8Q
runtime.cloth=zErG1kOw

deps.lambdynamiclights=4.12.4+26.2
deps.spruceui=11.0.0+26.2
target.sodium=0.9.2
